

create table IF NOT EXISTS INVEX.EMPLOYEES(
	id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	first_name varchar(50),
	second_name varchar(50),
	paternal_surname varchar(50),
	maternal_surname varchar(50),
	age number(2,0),
	gender varchar(1),
	birthdate date,
	position varchar(50),
	register_date timestamp DEFAULT SYSDATE,
	status boolean default TRUE
);

